name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.sm-version == '1.12.x' }}
    strategy:
      matrix:
        sm-version: [ '1.10.x', '1.11.x', '1.12.x' ]

    name: "Build SM ${{ matrix.sm-version }}"
    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          SMVERSION_FULL=${{ matrix.sm-version }}
          echo "SMVERSION_SHORT=${SMVERSION_FULL:0:-2}" >> $GITHUB_ENV
      - uses: actions/checkout@v3

      - name: Setup SP
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Run compiler
        run: |
          wget -O addons/sourcemod/scripting/include/shop.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop.inc"
          wget -O addons/sourcemod/scripting/include/shop/admin.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop/admin.inc"
          wget -O addons/sourcemod/scripting/include/shop/db.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop/db.inc"
          wget -O addons/sourcemod/scripting/include/shop/functions.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop/functions.inc"
          wget -O addons/sourcemod/scripting/include/shop/items.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop/items.inc"
          wget -O addons/sourcemod/scripting/include/shop/methodmaps.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop/methodmaps.inc"
          wget -O addons/sourcemod/scripting/include/shop/players.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop/players.inc"
          wget -O addons/sourcemod/scripting/include/shop/register.inc "https://raw.githubusercontent.com/hlmod/Shop-Core/master/addons/sourcemod/scripting/include/shop/register.inc"
          cd addons/sourcemod
          mkdir plugins
          cd scripting
          ls
          ls ./shop
          spcomp shop_equipments.sp -E -o ../plugins/shop_equipments.smx -iinclude ${{ matrix.compiler-options }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Shop-Equipments-${{ env.SMVERSION_SHORT }}-${{ env.GITHUB_SHA_SHORT }}
          path: |
            addons
            cfg
            LICENSE
          retention-days: 2

  release:
    name: Release
    if: github.ref_type == 'tag'
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Find Assets
        shell: bash
        run: |
          echo "artifact-1_10=$(find * -maxdepth 0 -type d -name "*1.10*")" >> $GITHUB_ENV
          echo "artifact-1_11=$(find * -maxdepth 0 -type d -name "*1.11*")" >> $GITHUB_ENV
          echo "artifact-1_12=$(find * -maxdepth 0 -type d -name "*1.12*")" >> $GITHUB_ENV
          
      - name: Arhive Assets
        run: |
          zip -r ${{ env.artifact-1_10 }}.zip ${{ env.artifact-1_10 }}
          zip -r ${{ env.artifact-1_11 }}.zip ${{ env.artifact-1_11 }}
          zip -r ${{ env.artifact-1_12 }}.zip ${{ env.artifact-1_12 }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Upload Asset for SM 1.10
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.artifact-1_10 }}.zip
          asset_name: ${{ env.artifact-1_10 }}.zip
          asset_content_type: application/zip

      - name: Upload Asset for SM 1.11
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.artifact-1_11 }}.zip
          asset_name: ${{ env.artifact-1_11 }}.zip
          asset_content_type: application/zip

      - name: Upload Asset for SM 1.12
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.artifact-1_12 }}.zip
          asset_name: ${{ env.artifact-1_12 }}.zip
          asset_content_type: application/zip
